### ISSUE TITLE
Add subview support

### ISSUE THREAD

**Issue by janciesko** [kokkos/kokkos-remote-spaces#16]
Subviews allow to encapsulate a subset of data on a partition _rank_.
We need to add support for both ways of subview construction:
```C++
auto v_sub = Kokkos::Experimental::RemoteSpaces::subview (v, rank, Args... dim);
auto v_sub = Kokkos::View<Data_t, RemoteSpace>(v, rank, Args... dim);
````
A subview is a stepping stone towards block data transfers. Up for discussion: 
- A subview return type is a View or a RemoteView:

**Comment by crtrott** [comment]
Subview problem for remote subview for local_deep_copy usecase:

```c++
View<double**,DefaultRemoteSpace> a("Label",numRanks,N);

auto a_sub_3 = subview(a,3,ALL); // How to make this work
```

Problem: right now first dimension is the rank.

Possible approach: RankedLayoutLeft/Right for what we do now.
LayoutLeft/LayoutRight store an offset for which rank to start with it
Works for range but what for hard index.

```c++
auto a_sub_3 = subview(a,pair(3,5),ALL); // How to make this work
// store rank_offset = 3
// store extent0_per_rank = a.extent0_per_rank == 1
a_sub_3(0,i);
// Mapping will do handle((0+rank_offset)/extent0_per_rank,mapping(0,i));

// Eliminating the rank works too because:
auto a_sub_3 = subview(a,3,ALL); // How to make this work
// store rank_offset = 3
// store extent0_per_rank = a.extent(1);
```
