### ISSUE TITLE
Tests failing with MPISpace

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos-remote-spaces#37]
There are multiple tests failing when using MPISpace, including localdeepcopy  and partitioned_subview. In particular, the problematic line in Test_LocalDeepCopy.cpp is [here](https://github.com/kokkos/kokkos-remote-spaces/blob/main/unit_tests/Test_LocalDeepCopy.cpp#L164). The test passes for the Scalar and the 1D View. Only the 2D View fails.

**Comment by janciesko** [comment]
[The overhaul PR](https://github.com/kokkos/kokkos-remote-spaces/pull/82) resolved this issue. I was not able to reproduce. We should probably add MPI testing along with shmem to CI as well.
