### ISSUE TITLE
(nv)shmem_ptr returning nill for multi-node execution on Lassen

### ISSUE THREAD

**Issue by janciesko** [kokkos/kokkos-remote-spaces#5]

**Comment by janciesko** [comment]
NVSHMEM returns an invalid pointer instead of nill when calling nvshmem_ptr() on non-accessible PEs. @akhillanger notified and working on patch.

**Comment by akhillanger** [comment]
@janciesko this bug has been fixed in NVSHMEM - will be included in the next NVSHMEM release.

**Comment by janciesko** [comment]
Closing.
